### ISSUE TITLE
Available as PPA or .deb?

### ISSUE THREAD

**Issue by aquatix** [Alecaddd/sequeler#31]
I'm not entirely sure if this is the right place, but it would be great if this neat client would be available outside elementary OS too, maybe in a PPA for Ubuntu, or some downloadable .deb?

I wanted to build it myself, but it appears that the dependencies are quite elementary OS-specific. If you can point me to how to build it for Debian or Ubuntu, I'll try a hand at it myself.

Thanks in advance!

**Comment by Alecaddd** [comment]
Hi, thanks for your interest in Sequeler.
I'm currently looking into releasing it as a deb via PPA, and Snap package.
I'm having similar issues in packaging it for non-elementaryOS distro, especially regarding the Granite library.
I should be able to release it next week.

**Comment by aquatix** [comment]
That's really good to hear! Please let me know if I can be of any help, if only for testing.

**Comment by Alecaddd** [comment]
Definitely, a help would be much appreciated.
I'm trying to build at first a Snap app, in order to make it available on any distro, and not only Ubuntu based.
I seem to have a problem with the `snapcraft.yml` file, not sure if you have any experience with it, or you know someone to ask for help.
This is my current setup

```
name: sequeler
version: '0.2.0'
summary: Friendly SQL Client
description: Store your Database Connections in the built-in library, type and execute SQL commands directly in the App, and do everything you need to do without the necessity of opening the terminal.
grade: stable
confinement: strict

apps:
  sequeler:
    command: sequeler

parts:
  sequeler:
    plugin: autotools
    source: git://github.com/alecaddd/sequeler.git
```
